import "../globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import StyledTheme from "@/utils/styledTheme";
import Slider from "@/components/home/slider/slider";
import NavbarHome from "@/components/home/navbar/navbar";
import FooterHome from "@/components/home/footer/footer";

export const metadata = {
  title: "Application Name",
  description: "Generated by create next app",
  icons: {
    icon: "/mcd.ico",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <StyledTheme>
            <div className="container">
              <NavbarHome />
              <div className="wrapper" >
                <Slider />
                <div className="main">{children}</div>
                <FooterHome />
              </div>
            </div>
          </StyledTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
