import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v13-appRouter";
import StyledTheme from "@/utils/styledTheme";
import Navbar from "@/components/navbar/navbar";
import { Stack } from "@mui/material";
import Sidebar from "@/components/sidebar/sidebar";
import theme from "@/utils/theme";

export const metadata = {
  title: "Application Name",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          <StyledTheme>
            <Navbar />
            <Stack direction="row" justifyContent="space-between">
              <Stack flex={1} bgcolor={theme.palette.secondary.light}>
                <Sidebar />
              </Stack>
              <Stack flex={6} sx={{m:2}}>{children}</Stack>
            </Stack>
          </StyledTheme>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
